
version: '3'

services:

### selenium Server Container ##################################

    selenium:
      image: selenium/standalone-chrome
      volumes:
        - ${NGINX_HTML_PATH}:/var/www/html
      expose:
        - "9000"
      depends_on:
        - nginx
      links:
        -  nginx:blog.dev
 
### Nginx Server Container ##################################

    nginx:
      image: jerichen/nginx:latest
      volumes:          
          - ${NGINX_SITE_CONF_PATH}:/etc/nginx/sites-available
          - ${NGINX_HTML_PATH}:/var/www/html
          - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      ports:
          - "${NGINX_HOST_HTTP_PORT}:80"
          - "${NGINX_HOST_HTTPS_PORT}:443"
      depends_on:
          - php-fpm-71
          - php-fpm-56
          - php-fpm-55

### PHP-FPM Container #######################################

    php-fpm-71:
      image: jerichen/php71:latest
      volumes:
        - ${NGINX_HTML_PATH}:/var/www/html
        - ${PHP_FPM_LOG_PATH}:/var/log/php-fpm
      depends_on:
          - mariadb

    php-fpm-56:
      image: jerichen/php56:latest
      volumes:
        - ${NGINX_HTML_PATH}:/var/www/html
        - ${PHP_FPM_LOG_PATH}:/var/log/php-fpm
      depends_on:
          - mariadb

    php-fpm-55:
      build:
        context: ./php-fpm
        dockerfile: "Dockerfile-55"
      volumes:
        - ${NGINX_HTML_PATH}:/var/www/html
        - ${PHP_FPM_LOG_PATH}:/var/log/php-fpm
        - ./php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini
      expose:
        - "9000"
      depends_on:
          - mariadb
          
### MySQL Container #########################################

    mariadb:
      image: mariadb:5.5.57
      ports:
        - "${MYSQL_PORT}:3306"
      volumes:
        - mysql-data:/var/lib/mysql
        - ${MYSQL_LOG_PATH}:/var/log/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}

### Redis Container #########################################

    redis:
      image: redis
      volumes:
        - ${REDIS_LOG_PATH}:/var/log/redis
      ports:
        - "${REDIS_PORT}:6379"
        
### selenium Server Container ##################################

    selenium-hub:
        image: selenium/hub  
        volumes:
          - ${SELENIUM_LOG_PATH}:/var/log/selenium        
        ports:
          - "${SELENIUM_PORT}:4444"
        expose:
          - "9000"
        depends_on:
          - nginx
          
    chrome:
        image: selenium/node-chrome-debug
        environment:
          HUB_PORT_4444_TCP_ADDR: 'hub'
          HUB_PORT_4444_TCP_PORT: 4444
          NODE_MAX_INSTANCES: 3
          NODE_MAX_SESSION: 3
        links:          
          - selenium-hub:hub
          - nginx:blog.dev
          
    firefox:
        image: selenium/node-firefox-debug
        environment:
          HUB_PORT_4444_TCP_ADDR: 'hub'
          HUB_PORT_4444_TCP_PORT: 4444
          NODE_MAX_INSTANCES: 3
          NODE_MAX_SESSION: 3
        links:          
          - selenium-hub:hub
          - nginx:blog.dev

### Volumes Settings #########################################
volumes:
  mysql-data:
